# Default config for Arcania plugin
enchant:
  enrichment:
    xp-multiplier:
      - 0.75
      - 1.0
      - 1.5
    k: 10.0
    base-cutoff: 5
  essence:
    xp-multiplier:
      - 0.75
      - 1.0
      - 1.5
    k: 10.0
    base-cutoff: 5
  veinminer:
    max-blocks: 10
    whitelisted-blocks:
      - '*_ORE'
      - STONE
      - ANCIENT_DEBRIS
      - GRANITE
      - DIORITE
      - ANDESITE
      - TUFF
      - DEEPSLATE
      - NETHERRACK
  smelt:
    blacklisted-blocks:
      - '*_ORE' #Prevents silk touched ore from being smelted
enchants-included:
  - Quarry
  - Tiller
  - Prosperity
  - Blink
  - Enrichment
  - Harvester
  - Frostbite
  - Veinminer
  - Magnet
  - Essence
  - Smelt