# Default config for Arcania plugin
utility:
  fix-enchant-check: false

enchant:
  veinminer:
    max-blocks: 10
    whitelisted-blocks:
      - '*_ORE'
      - STONE
      - ANCIENT_DEBRIS
      - GRANITE
      - DIORITE
      - ANDESITE
      - TUFF
      - DEEPSLATE
      - NETHERRACK