name: Arcania
version: '1.0'
main: me.vout.paper.arcania.Arcania
description: Custom enchants plugin
api-version: '1.21.5'
bootstrapper: me.vout.paper.arcania.ArcaniaBootstrap
# loader: me.vout.paper.arcania.ArcaniaLoader