name: Arcania
version: '${project.version}'
main: me.vout.paper.arcania.Arcania
api-version: '1.21'
load: STARTUP
authors: [Vout, Lmvdzande]
description: Custom enchants plugin
commands:
  arcania:
    description: Main command for Arcania plugin
    usage: /<command> [reload|menu|tinkerer|disenchanter|enchanter|enchants|tester]
    permission: arcania.use
  enchants:
    description: Opens the enchants menu
    usage: /<command>
    permission: arcania.menu.enchants
  tester:
    description: Gives access to all enchants for testing
    usage: /<command>
    permission: arcania.menu.tester

permissions:
  arcania.*:
    description: Allows access to Arcania Enchants
    default: op

  arcania.use:
    description: Allows access to use base /arcania command
    default: true

  arcania.reload:
    description: Allows reloading the plugin
    default: op

  arcania.menu.tester:
    description: Allows access to tester menu
    default: op

  arcania.menu:
    description: Gives access to the menus
    default: true
    children:
      arcania.menu.base: true
      arcania.menu.enchants: true